FROM python:3.12

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

RUN mkdir -p logs

COPY container3.py .
COPY sentences.json .

CMD ["python3", "container3.py"]
