verion: '3.8'

services:
  #node.js server definieren:
  node-server:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mongo-db


  #MongoDB
  mongo-db:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"


volumes: 
  mongo-data: